<?php
include("./include/connection.php");
require("./fpdf.php");

function getCurrentDate()
{
    date_default_timezone_set('Asia/Kolkata');
    return date('Y-m-d');
}

// Get order ID from URL
if (!isset($_GET['order_id'])) {
    die('Order ID not provided.');
}
$order_id = intval($_GET['order_id']);

// Fetch order info
$order_sql = "SELECT o.*, u.fullname, u.email
              FROM tbl_order o
              JOIN tbl_user u ON o.user_id = u.id
              WHERE o.id = $order_id";
$order_result = mysqli_query($conn, $order_sql);
if (!$order_result || mysqli_num_rows($order_result) == 0) {
    die('Order not found.');
}
$order = mysqli_fetch_assoc($order_result);

// Get billing address/customer info
$customer = $order['fullname'];
$address = $order['address'];
$city = ""; // If you want, join tblcity/tblstate for more location details
$invoiceNumber = $order['order_number'];
$today = getCurrentDate();
$total_amt = $order['amount'];
$payer_email = $order['payer_email'];

// Prepare info array
$info = [
    "customer"    => $customer,
    "address"     => $address,
    "city"        => $city,
    "invoice_no"  => $invoiceNumber,
    "order_no"    => $invoiceNumber,
    "invoice_date"=> $today,
    "total_amt"   => number_format($total_amt, 2),
    "payer_email" => $payer_email,
];

// Fetch all order items for this order
$items = [];
$items_sql = "SELECT oi.*, p.name, u.unit_name
              FROM tbl_order_items oi
              JOIN tbl_products p ON oi.product_id = p.product_id
              JOIN tbl_unit u ON oi.variant_unit_id = u.unit_id
              WHERE oi.order_id = $order_id";
$items_result = mysqli_query($conn, $items_sql);

while ($row = mysqli_fetch_assoc($items_result)) {
    $items[] = [
        'name' => $row['name'] . " ({$row['variant_quantity']} {$row['unit_name']})",
        'price' => $row['price'],
        'qty' => $row['quantity'],
        'total' => $row['price'] * $row['quantity'],
    ];
}

// --- FPDF Section ---
class PDF extends FPDF
{
    function Header()
    {
        $this->SetFont('Arial', 'B', 14);
        $this->Cell(50, 10, "Wohl Reactions", 0, 1);
        $this->SetFont('Arial', '', 14);
        $this->Cell(50, 7, "203-Andarill Complex", 0, 1);
        $this->Cell(50, 7, "Thane, Mumbai 485612.", 0, 1);
        $this->Cell(50, 7, "PH  +91 78610 25980", 0, 1);
        $this->SetY(15);
        $this->SetX(-100);
        $this->SetFont('Arial', 'B', 24);
        $this->Cell(50, 20, "CUSTOMER INVOICE", 0, 1);
        $this->Line(0, 48, 210, 48);
    }
    function body($info, $items)
    {
        $this->SetY(55);
        $this->SetX(10);
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(50, 10, "Bill To: ", 0, 1);
        $this->SetFont('Arial', '', 12);
        $this->Cell(50, 7, $info["customer"], 0, 1);
        $this->Cell(50, 7, $info["address"], 0, 1);
        $this->Cell(50, 7, $info["city"], 0, 1);
        $this->Cell(50, 7, $info["payer_email"], 0, 1);

        $this->SetY(55);
        $this->SetX(-80);
        $this->Cell(50, 7, "Invoice No : " . $info["invoice_no"]);
        $this->SetY(63);
        $this->SetX(-80);
        $this->Cell(50, 7, "Invoice Date : " . $info["invoice_date"]);

        // Table Headers
        $this->SetY(95);
        $this->SetX(10);
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(80, 9, "DESCRIPTION", 1, 0);
        $this->Cell(40, 9, "PRICE", 1, 0, "C");
        $this->Cell(30, 9, "QTY", 1, 0, "C");
        $this->Cell(40, 9, "TOTAL", 1, 1, "C");
        $this->SetFont('Arial', '', 12);

        // Table Rows
        foreach($items as $item) {
            $this->SetX(10);
            $this->Cell(80, 9, $item['name'], 1, 0);
            $this->Cell(40, 9, number_format($item['price'],2), 1, 0, "C");
            $this->Cell(30, 9, $item['qty'], 1, 0, "C");
            $this->Cell(40, 9, number_format($item['total'],2), 1, 1, "C");
        }
        // Grand Total Row
        $this->SetX(10);
        $this->Cell(150, 9, "Grand Total", 1, 0, "R");
        $this->Cell(40, 9, number_format($info['total_amt'],2), 1, 1, "C");
    }
    function Footer()
    {
        $this->SetY(-50);
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 10, "for Wohl Reactions", 0, 1, "R");
        $this->Ln(15);
        $this->SetFont('Arial', '', 12);
        $this->Cell(0, 10, "Authorized Signature", 0, 1, "R");
        $this->SetFont('Arial', '', 10);
        $this->Cell(0, 10, "Invoice Generated By Wohl Reactions...", 0, 1, "C");
    }
}

$pdf = new PDF("P", "mm", "A4");
$pdf->AddPage();
$pdf->body($info, $items);
ob_end_clean();
$pdf->Output();
?>